jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - assignments: 
          - "chocolateen"
          name: "admin"
          pattern: ".*"
          permissions:
            - "Job/Move"
            - "Job/Build"
            - "Credentials/Delete"
            - "Credentials/ManageDomains"
            - "View/Create"
            - "Agent/Configure"
            - "Job/Read"
            - "Credentials/Update"
            - "Agent/Create"
            - "Job/Delete"
            - "Agent/Build"
            - "View/Configure"
            - "Agent/Provision"
            - "SCM/Tag"
            - "Job/Create"
            - "Job/Discover"
            - "Credentials/View"
            - "Agent/Connect"
            - "Agent/Delete"
            - "Agent/Disconnect"
            - "Run/Delete"
            - "Job/Cancel"
            - "Overall/Read"
            - "Run/Update"
            - "Credentials/Create"
            - "Overall/Administer"
            - "View/Delete"
            - "Job/Configure"
            - "Job/Workspace"
            - "View/Read"
        - assignments:
          - "i_dont_know"
          name: "ape"
          pattern: ".*"
          permissions:
            - "Overall/Read"
            - "Job/Read"
            - "Job/Build"
            - "Job/Workspace"
        - assignments:
          - "vaugie_g"
          name: "gorilla"
          pattern: ".*"
          permissions:
            - "Overall/Read"
            - "Job/Read"
            - "Job/Move"
            - "Job/Build"
            - "Job/Delete"
            - "Job/Create"
            - "Job/Configure"
            - "Job/Workspace"
            - "Job/Cancel"
        - assignments:
          - "nasso"
          name: "assist"
          pattern: ".*"
          permissions:
            - "Overall/Read"
            - "Job/Read"
            - "Job/Workspace"              
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "chocolateen"
        password: ${USER_CHOCOLATEEN_PASSWORD}
        name: "Hugo"
      - id: "vaugie_g"
        password: ${USER_VAUGIE_G_PASSWORD}
        name: "Garance"
      - id: "i_dont_know"
        password: ${USER_I_DONT_KNOW_PASSWORD}
        name: "Jeremy"
      - id: "nasso"
        password: ${USER_NASSO_PASSWORD}
        name: "Nassim"
        
jobs:
  - url: "https://raw.githubusercontent.com/Gillian-B/Jenkins-test/master/job_dsl2.groovy"
