jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
      - id: "chocolateen"
        password: ${USER_CHOCOLATEEN_PASSWORD}
        name: "Hugo"
      - id: "vaugie_g"
        password: ${USER_VAUGIE_G_PASSWORD}
        name: "Garance"
      - id: "i_dont_know"
        password: ${USER_I_DONT_KNOW_PASSWORD}
        name: "Jeremy"
      - id: "nasso"
        password: ${USER_NASSO_PASSWORD}
        name: "Nassim"
        
jobs:
  - url: "https://raw.githubusercontent.com/Gillian-B/Jenkins-test/master/job_dsl2.groovy"
